### PR TITLE
general-concepts/use-flags: give guidance on IUSE defaults

### PR DESCRIPTION
**Pull request by thesamesam**
Signed-off-by: Sam James <sam@gentoo.org>

### CODE REVIEW

**Comment by orlitzky** [comment]
Because portage treats flags as off by default, and because of the default `USE_ORDER`, it's _much_ harder for people to disable flags that are default-on than it is for them to enable flags that are not.

Making this a de-facto policy is really annoying for the people who want to enable only what they want and leave everything else off. (That said, it's already a pain in the ass, because every maintainer does whatever he wants at the moment, and many use `IUSE` defaults as their own personal `make.conf` replacement.)

A policy like "`IUSE` defaults should only be set when the package would otherwise be severely handicapped" would be more in line with our tooling.

**Comment by orlitzky** [comment]
Also, in my experience, many upstreams use `configure.ac` as their own personal `make.conf` replacement. In those cases, standardizing what the main developer likes to use on his machine isn't going to produce very consistent results.

**Comment by sbraz** [comment]
> A policy like "IUSE defaults should only be set when the package would otherwise be severely handicapped" would be more in line with our tooling.

I like the general idea.

**Comment by thesamesam** [comment]
yes, that alternative is fine with me

**Review by ulm — APPROVED** [review]

**Pull request closed without merging**
